### ISSUE TITLE
Readme is wrong

### ISSUE THREAD

**Issue by machenchi0207** [alberto-bottarini/httpdispatcher#10]
## Example in the Readme is wrong
```javascript
var dispatcher = require('./httpdispatcher');
	
	dispatcher.setStatic('resources');
```
here need a statment like this:
```javascript
var dispatcher = require('./httpdispatcher');
	
	dispatcher.setStatic('resources');
//this statment!
dispatcher.setStaticDirname('.');
```
otherwise node will report an Error of package 'Path'.Because the variable in httpdipatcher.js ``this.staticDirname``

**Comment by generalandrew** [comment]
I pointed the require statement to my local node_modules directory 

    var dispatcher = require('./node_modules/httpdispatcher');

**Comment by alberto-bottarini** [comment]
Thanks
