### ISSUE TITLE
Load resource issue

### ISSUE THREAD

**Issue by renamed** [alberto-bottarini/httpdispatcher#20]
For relative path, anything different from `dispatcher.setStaticDirname('');` makes _httpdispatcher_ unable to find the pages resources. They just do not get loaded.

This is due to line number 79 in httpdispatcher.js in which it is found

`var filename = "." + require('path').join(this.staticDirname, url.pathname);`

If static dir name is not set, an exception is thrown. If it is set to anything but an empty string for relative paths, it prepends a '.' to the beggining of the resource path, making it unable to be found.
## Scenario 1

```
dispatcher.setStaticDirname(__dirname);
dispatcher.setStatic('resources');
```

Resource path: 

> .C:\Users\Renato\Desktop\resources\aeee.png
## Scenario 2

```
dispatcher.setStaticDirname('.');
dispatcher.setStatic('resources');
```

Resource path: 

> .resources\aeee.png
## Scenario 3

This is the only one that works.

```
dispatcher.setStaticDirname('');
dispatcher.setStatic('resources');
```

Resource path: 

> .\resources\aeee.png

**Comment by renamed** [comment]
Btw, I'm using Windows 10. Not sure if Unix-based systems are prone to this issue.

**Comment by stefke314** [comment]
I have the same issue on my Linux system.

**Comment by Plazmaz** [comment]
Logical Workaround: Remove the "." if using a relative path. Seems to work on windows.
It's annoying in terms of deployment, but thankfully this project only requires the one file to run.

**Comment by alberto-bottarini** [comment]
Please upgrade to 2.0.1 and tell me if this error still occurs. Thanks
