### ISSUE TITLE
ReferenceError: chain is not defined

### ISSUE THREAD

**Issue by kjenney** [alberto-bottarini/httpdispatcher#21]
I copied and pasted the example and tried running it on node v6.2.1 and I got the ReferenceError error for chain. I see that there was an issue open that is now closed. 

How can I resolve this error?

**Comment by kjenney** [comment]
I just removed the filter entries do get past it. But shouldn't they work out of the box? Does your example need to be updated?

**Comment by gtatyous93** [comment]
do you know how to make the dispatcher accept any url request?

**Comment by alberto-bottarini** [comment]
Please upgrade to 2.0.1 version and tell me if same error still occurs.
