### ISSUE TITLE
ReferenceError: chain is not defined

### ISSUE THREAD

**Issue by molinto** [alberto-bottarini/httpdispatcher#4]
In your readme example, it uses 'chain'.  Where/what is this please?

**Comment by alberto-bottarini** [comment]
chain is an instance of HttpChain, a custom object.
In the bottom of httpdispatcher.js you can see its implementation.

I know, I should create a better documentationn :sweat_smile:

**Comment by molinto** [comment]
Thanks, do I need to initialise it somehow?
Also, does this power the 404 response as that never seems to come up for me?

Thanks

**Comment by alberto-bottarini** [comment]
No, you should only call ```next``` method inside your filter if you want to continue the standard dispatcher process.
If you want to define a custom 404 behaviour you should use ```onError``` event

**Comment by molinto** [comment]
Ok thanks

**Comment by kjenney** [comment]
The example shouldn't cause errors. It should work. I don't understand why this is still there if it's not correct.
