### ISSUE TITLE
No Support for TypeScript

### ISSUE THREAD

**Issue by cjbarth** [alberto-bottarini/httpdispatcher#6]
I noticed that there is no TypeScript support for this module either in your project or in DefinitelyTyped. Thus, I created a httpdispatcher.d.ts file for you to include in your project. I didn't include it in DefinitelyTyped's repository because I don't care to write all those tests. If you'd like the file in your project for all us TypeScript users, I'd be glad to make a PR.

**Comment by alberto-bottarini** [comment]
I'm not an expert of TypeScript but I think it's a good idea. Go ahead with PR. Thanks :+1:

**Comment by cjbarth** [comment]
See PR #7 for definitions

**Comment by tommck** [comment]
So... is this going to get merged?

**Comment by FizzyGalacticus** [comment]
This issue has been resolved -- all pull requests were merged last week.

**Comment by kbirger** [comment]
The package.json is missing a typings field, so typescript will not find the type definition.
